<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RammohanN-PC" name="com.ktpl.testcases.LoginpageTest" tests="4" failures="1" timestamp="2020-06-26T13:45:10 IST" time="103.902" errors="0">
  <testcase name="LoginpagetitleTest" time="22.340" classname="com.ktpl.testcases.LoginpageTest"/>
  <testcase name="CustomerloginTest" time="32.012" classname="com.ktpl.testcases.LoginpageTest">
    <failure type="java.lang.AssertionError" message="login is not sucessfull expected [Home Page] but found [My Account]">
      <![CDATA[java.lang.AssertionError: login is not sucessfull expected [Home Page] but found [My Account]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.ktpl.testcases.LoginpageTest.CustomerloginTest(LoginpageTest.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CustomerloginTest -->
  <testcase name="forgotpasswordlinkTest" time="24.725" classname="com.ktpl.testcases.LoginpageTest"/>
  <testcase name="CreateaccountlinkTest" time="24.825" classname="com.ktpl.testcases.LoginpageTest"/>
</testsuite> <!-- com.ktpl.testcases.LoginpageTest -->
